const fs = require('fs');
const path = require('path');

const configs = [
  {
    examsDir: path.join(__dirname, '../data/paph/exams'),
    outputFile: path.join(__dirname, '../src/exams_index.ts'),
    baseVar: 'examsIndex',
    loaderVar: 'examLoaders',
  },
  {
    examsDir: path.join(__dirname, '../data/sphu/exams'),
    outputFile: path.join(__dirname, '../src/exams_sphu_index.ts'),
    baseVar: 'examsSphuIndex',
    loaderVar: 'examsSphuLoaders',
  },
];

for (const { examsDir, outputFile, baseVar, loaderVar } of configs) {
  const files = fs.readdirSync(examsDir).filter(f => f.endsWith('.json'));

  let indexEntries = [];
  let loaderEntries = [];

  for (const file of files) {
    const filePath = path.join(examsDir, file);
    const content = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    const title = file.replace('.json', '');
    const dirRel = path.relative(path.join(__dirname, '..', 'src'), examsDir).replace(/\\/g, '/');
    const importPath = `${dirRel}/${file}`;

    indexEntries.push({
      id: importPath,
      title: title,
      count: content.length
    });

    loaderEntries.push(`  '${importPath}': () => import('${importPath}'),`);
  }

  const fileContent = `// This file is auto-generated by scripts/generate_exams_index.cjs.
// Do not edit manually.

export interface ExamIndexItem {
  id: string;
  title: string;
  count: number;
}

export const ${baseVar}: ExamIndexItem[] = ${JSON.stringify(indexEntries, null, 2)};

export const ${loaderVar}: Record<string, () => Promise<any>> = {
${loaderEntries.join('\n')}
};
`;

  fs.writeFileSync(outputFile, fileContent, 'utf8');
  console.log(`Successfully generated ${path.relative(path.join(__dirname, '..'), outputFile)} with ${indexEntries.length} exams.`);
}