// This file is auto-generated by scripts/generate_exams_index.cjs.
// Do not edit manually.

export interface ExamIndexItem {
  id: string;
  title: string;
  count: number;
}

export const examsSphuIndex: ExamIndexItem[] = [
  {
    "id": "../data/sphu/exams/การติดตั้งและบำรุงรักษาคอมพิวเตอร์ส่วนบุคคล.json",
    "title": "การติดตั้งและบำรุงรักษาคอมพิวเตอร์ส่วนบุคคล",
    "count": 100
  },
  {
    "id": "../data/sphu/exams/ความมั่นคงปลอดภัยสารสนเทศ และการบริหารความเสี่ยง.json",
    "title": "ความมั่นคงปลอดภัยสารสนเทศ และการบริหารความเสี่ยง",
    "count": 100
  },
  {
    "id": "../data/sphu/exams/พ.ร.บ. คอมพิวเตอร์ และกฎหมายที่เกี่ยวข้อง.json",
    "title": "พ.ร.บ. คอมพิวเตอร์ และกฎหมายที่เกี่ยวข้อง",
    "count": 100
  },
  {
    "id": "../data/sphu/exams/ภาษาคอมพิวเตอร์ และการเขียนโปรแกรม.json",
    "title": "ภาษาคอมพิวเตอร์ และการเขียนโปรแกรม",
    "count": 100
  },
  {
    "id": "../data/sphu/exams/ระบบปฏิบัติการและซอฟต์แวร์สำเร็จรูป.json",
    "title": "ระบบปฏิบัติการและซอฟต์แวร์สำเร็จรูป",
    "count": 100
  },
  {
    "id": "../data/sphu/exams/ระบบสารสนเทศ การวิเคราะห์ระบบ และฐานข้อมูล.json",
    "title": "ระบบสารสนเทศ การวิเคราะห์ระบบ และฐานข้อมูล",
    "count": 100
  },
  {
    "id": "../data/sphu/exams/ระบบเครือข่ายคอมพิวเตอร์ และอุปกรณ์ที่เกี่ยวข้อง.json",
    "title": "ระบบเครือข่ายคอมพิวเตอร์ และอุปกรณ์ที่เกี่ยวข้อง",
    "count": 100
  }
];

export const examsSphuLoaders: Record<string, () => Promise<any>> = {
  '../data/sphu/exams/การติดตั้งและบำรุงรักษาคอมพิวเตอร์ส่วนบุคคล.json': () => import('../data/sphu/exams/การติดตั้งและบำรุงรักษาคอมพิวเตอร์ส่วนบุคคล.json'),
  '../data/sphu/exams/ความมั่นคงปลอดภัยสารสนเทศ และการบริหารความเสี่ยง.json': () => import('../data/sphu/exams/ความมั่นคงปลอดภัยสารสนเทศ และการบริหารความเสี่ยง.json'),
  '../data/sphu/exams/พ.ร.บ. คอมพิวเตอร์ และกฎหมายที่เกี่ยวข้อง.json': () => import('../data/sphu/exams/พ.ร.บ. คอมพิวเตอร์ และกฎหมายที่เกี่ยวข้อง.json'),
  '../data/sphu/exams/ภาษาคอมพิวเตอร์ และการเขียนโปรแกรม.json': () => import('../data/sphu/exams/ภาษาคอมพิวเตอร์ และการเขียนโปรแกรม.json'),
  '../data/sphu/exams/ระบบปฏิบัติการและซอฟต์แวร์สำเร็จรูป.json': () => import('../data/sphu/exams/ระบบปฏิบัติการและซอฟต์แวร์สำเร็จรูป.json'),
  '../data/sphu/exams/ระบบสารสนเทศ การวิเคราะห์ระบบ และฐานข้อมูล.json': () => import('../data/sphu/exams/ระบบสารสนเทศ การวิเคราะห์ระบบ และฐานข้อมูล.json'),
  '../data/sphu/exams/ระบบเครือข่ายคอมพิวเตอร์ และอุปกรณ์ที่เกี่ยวข้อง.json': () => import('../data/sphu/exams/ระบบเครือข่ายคอมพิวเตอร์ และอุปกรณ์ที่เกี่ยวข้อง.json'),
};
