// This file is auto-generated by scripts/generate_exams_index.cjs.
// Do not edit manually.

export interface ExamIndexItem {
  id: string;
  title: string;
  count: number;
}

export const examsIndex: ExamIndexItem[] = [
  {
    "id": "../data/paph/exams/English 1.json",
    "title": "English 1",
    "count": 80
  },
  {
    "id": "../data/paph/exams/English 2.json",
    "title": "English 2",
    "count": 84
  },
  {
    "id": "../data/paph/exams/Microsoft office.json",
    "title": "Microsoft office",
    "count": 50
  },
  {
    "id": "../data/paph/exams/กรม ปภ.json",
    "title": "กรม ปภ",
    "count": 48
  },
  {
    "id": "../data/paph/exams/การงบประมาณ.json",
    "title": "การงบประมาณ",
    "count": 49
  },
  {
    "id": "../data/paph/exams/การจัดทำงบประมาณ.json",
    "title": "การจัดทำงบประมาณ",
    "count": 50
  },
  {
    "id": "../data/paph/exams/การจัดทำแผนงานและโครงการ.json",
    "title": "การจัดทำแผนงานและโครงการ",
    "count": 50
  },
  {
    "id": "../data/paph/exams/การจัดทำแผนเชิงกลยุทธ์.json",
    "title": "การจัดทำแผนเชิงกลยุทธ์",
    "count": 49
  },
  {
    "id": "../data/paph/exams/การติดตามและประเมินผล.json",
    "title": "การติดตามและประเมินผล",
    "count": 49
  },
  {
    "id": "../data/paph/exams/การบริหารความเสี่ยง.json",
    "title": "การบริหารความเสี่ยง",
    "count": 47
  },
  {
    "id": "../data/paph/exams/การบริหารจัดการสาธารณภัย.json",
    "title": "การบริหารจัดการสาธารณภัย",
    "count": 48
  },
  {
    "id": "../data/paph/exams/การวิเคราะห์นโยบายสาธารณะ.json",
    "title": "การวิเคราะห์นโยบายสาธารณะ",
    "count": 50
  },
  {
    "id": "../data/paph/exams/การเมือง เศรษฐกิจและสังคม.json",
    "title": "การเมือง เศรษฐกิจและสังคม",
    "count": 48
  },
  {
    "id": "../data/paph/exams/การใช้คอมพิวเตอร์เบื้องต้น.json",
    "title": "การใช้คอมพิวเตอร์เบื้องต้น",
    "count": 50
  },
  {
    "id": "../data/paph/exams/การใช้อุปกรณ์สำนักงาน.json",
    "title": "การใช้อุปกรณ์สำนักงาน",
    "count": 49
  },
  {
    "id": "../data/paph/exams/การใช้เทคโนโลยีดิจิทัล คอมพิวเตอร์.json",
    "title": "การใช้เทคโนโลยีดิจิทัล คอมพิวเตอร์",
    "count": 50
  },
  {
    "id": "../data/paph/exams/การใช้ไวยากรณ์.json",
    "title": "การใช้ไวยากรณ์",
    "count": 100
  },
  {
    "id": "../data/paph/exams/นโยบายรัฐบาล.json",
    "title": "นโยบายรัฐบาล",
    "count": 48
  },
  {
    "id": "../data/paph/exams/พรบ ข้อมูลข่าวสาร.json",
    "title": "พรบ ข้อมูลข่าวสาร",
    "count": 100
  },
  {
    "id": "../data/paph/exams/พรบ ข้าราชการพลเรือน.json",
    "title": "พรบ ข้าราชการพลเรือน",
    "count": 146
  },
  {
    "id": "../data/paph/exams/พรบ บริหารราชการแผ่นดิน.json",
    "title": "พรบ บริหารราชการแผ่นดิน",
    "count": 150
  },
  {
    "id": "../data/paph/exams/พรบ ปรับปรุงกระทรวง ทบวง กรม .json",
    "title": "พรบ ปรับปรุงกระทรวง ทบวง กรม ",
    "count": 90
  },
  {
    "id": "../data/paph/exams/พรบ ป้องกันและบรรเทาสาธารณภัย.json",
    "title": "พรบ ป้องกันและบรรเทาสาธารณภัย",
    "count": 128
  },
  {
    "id": "../data/paph/exams/พรบ วิธีการงบประมาณ.json",
    "title": "พรบ วิธีการงบประมาณ",
    "count": 100
  },
  {
    "id": "../data/paph/exams/ยุทธศาสตร์ชาติ 20 ปี.json",
    "title": "ยุทธศาสตร์ชาติ 20 ปี",
    "count": 45
  },
  {
    "id": "../data/paph/exams/ระเบียบป้องกันลดอุบัติเหตุทางถนน.json",
    "title": "ระเบียบป้องกันลดอุบัติเหตุทางถนน",
    "count": 100
  },
  {
    "id": "../data/paph/exams/ระเบียบป้องกันอุบัติภัย.json",
    "title": "ระเบียบป้องกันอุบัติภัย",
    "count": 38
  },
  {
    "id": "../data/paph/exams/ระเบียบอาสาสมัครป้องกันภัย .json",
    "title": "ระเบียบอาสาสมัครป้องกันภัย ",
    "count": 99
  },
  {
    "id": "../data/paph/exams/ระเบียบานสารบรรณ.json",
    "title": "ระเบียบานสารบรรณ",
    "count": 149
  },
  {
    "id": "../data/paph/exams/ระเบียบเงินช่วยเหลือผู้ประสบภัย.json",
    "title": "ระเบียบเงินช่วยเหลือผู้ประสบภัย",
    "count": 99
  },
  {
    "id": "../data/paph/exams/ระเบียบเตือนภัยพิบัติ.json",
    "title": "ระเบียบเตือนภัยพิบัติ",
    "count": 68
  },
  {
    "id": "../data/paph/exams/วิชาภาษาอังกฤษ .json",
    "title": "วิชาภาษาอังกฤษ ",
    "count": 50
  },
  {
    "id": "../data/paph/exams/สถานการณ์สาธารณภัย.json",
    "title": "สถานการณ์สาธารณภัย",
    "count": 49
  },
  {
    "id": "../data/paph/exams/เทคโนโลยีและเครื่องมือวิเคราะห์.json",
    "title": "เทคโนโลยีและเครื่องมือวิเคราะห์",
    "count": 50
  },
  {
    "id": "../data/paph/exams/แผนการป้องกันภัยแห่งชาติ .json",
    "title": "แผนการป้องกันภัยแห่งชาติ ",
    "count": 74
  },
  {
    "id": "../data/paph/exams/แผนพัฒนาเศรษฐกิจและสังคม.json",
    "title": "แผนพัฒนาเศรษฐกิจและสังคม",
    "count": 54
  }
];

export const examLoaders: Record<string, () => Promise<any>> = {
  '../data/paph/exams/English 1.json': () => import('../data/paph/exams/English 1.json'),
  '../data/paph/exams/English 2.json': () => import('../data/paph/exams/English 2.json'),
  '../data/paph/exams/Microsoft office.json': () => import('../data/paph/exams/Microsoft office.json'),
  '../data/paph/exams/กรม ปภ.json': () => import('../data/paph/exams/กรม ปภ.json'),
  '../data/paph/exams/การงบประมาณ.json': () => import('../data/paph/exams/การงบประมาณ.json'),
  '../data/paph/exams/การจัดทำงบประมาณ.json': () => import('../data/paph/exams/การจัดทำงบประมาณ.json'),
  '../data/paph/exams/การจัดทำแผนงานและโครงการ.json': () => import('../data/paph/exams/การจัดทำแผนงานและโครงการ.json'),
  '../data/paph/exams/การจัดทำแผนเชิงกลยุทธ์.json': () => import('../data/paph/exams/การจัดทำแผนเชิงกลยุทธ์.json'),
  '../data/paph/exams/การติดตามและประเมินผล.json': () => import('../data/paph/exams/การติดตามและประเมินผล.json'),
  '../data/paph/exams/การบริหารความเสี่ยง.json': () => import('../data/paph/exams/การบริหารความเสี่ยง.json'),
  '../data/paph/exams/การบริหารจัดการสาธารณภัย.json': () => import('../data/paph/exams/การบริหารจัดการสาธารณภัย.json'),
  '../data/paph/exams/การวิเคราะห์นโยบายสาธารณะ.json': () => import('../data/paph/exams/การวิเคราะห์นโยบายสาธารณะ.json'),
  '../data/paph/exams/การเมือง เศรษฐกิจและสังคม.json': () => import('../data/paph/exams/การเมือง เศรษฐกิจและสังคม.json'),
  '../data/paph/exams/การใช้คอมพิวเตอร์เบื้องต้น.json': () => import('../data/paph/exams/การใช้คอมพิวเตอร์เบื้องต้น.json'),
  '../data/paph/exams/การใช้อุปกรณ์สำนักงาน.json': () => import('../data/paph/exams/การใช้อุปกรณ์สำนักงาน.json'),
  '../data/paph/exams/การใช้เทคโนโลยีดิจิทัล คอมพิวเตอร์.json': () => import('../data/paph/exams/การใช้เทคโนโลยีดิจิทัล คอมพิวเตอร์.json'),
  '../data/paph/exams/การใช้ไวยากรณ์.json': () => import('../data/paph/exams/การใช้ไวยากรณ์.json'),
  '../data/paph/exams/นโยบายรัฐบาล.json': () => import('../data/paph/exams/นโยบายรัฐบาล.json'),
  '../data/paph/exams/พรบ ข้อมูลข่าวสาร.json': () => import('../data/paph/exams/พรบ ข้อมูลข่าวสาร.json'),
  '../data/paph/exams/พรบ ข้าราชการพลเรือน.json': () => import('../data/paph/exams/พรบ ข้าราชการพลเรือน.json'),
  '../data/paph/exams/พรบ บริหารราชการแผ่นดิน.json': () => import('../data/paph/exams/พรบ บริหารราชการแผ่นดิน.json'),
  '../data/paph/exams/พรบ ปรับปรุงกระทรวง ทบวง กรม .json': () => import('../data/paph/exams/พรบ ปรับปรุงกระทรวง ทบวง กรม .json'),
  '../data/paph/exams/พรบ ป้องกันและบรรเทาสาธารณภัย.json': () => import('../data/paph/exams/พรบ ป้องกันและบรรเทาสาธารณภัย.json'),
  '../data/paph/exams/พรบ วิธีการงบประมาณ.json': () => import('../data/paph/exams/พรบ วิธีการงบประมาณ.json'),
  '../data/paph/exams/ยุทธศาสตร์ชาติ 20 ปี.json': () => import('../data/paph/exams/ยุทธศาสตร์ชาติ 20 ปี.json'),
  '../data/paph/exams/ระเบียบป้องกันลดอุบัติเหตุทางถนน.json': () => import('../data/paph/exams/ระเบียบป้องกันลดอุบัติเหตุทางถนน.json'),
  '../data/paph/exams/ระเบียบป้องกันอุบัติภัย.json': () => import('../data/paph/exams/ระเบียบป้องกันอุบัติภัย.json'),
  '../data/paph/exams/ระเบียบอาสาสมัครป้องกันภัย .json': () => import('../data/paph/exams/ระเบียบอาสาสมัครป้องกันภัย .json'),
  '../data/paph/exams/ระเบียบานสารบรรณ.json': () => import('../data/paph/exams/ระเบียบานสารบรรณ.json'),
  '../data/paph/exams/ระเบียบเงินช่วยเหลือผู้ประสบภัย.json': () => import('../data/paph/exams/ระเบียบเงินช่วยเหลือผู้ประสบภัย.json'),
  '../data/paph/exams/ระเบียบเตือนภัยพิบัติ.json': () => import('../data/paph/exams/ระเบียบเตือนภัยพิบัติ.json'),
  '../data/paph/exams/วิชาภาษาอังกฤษ .json': () => import('../data/paph/exams/วิชาภาษาอังกฤษ .json'),
  '../data/paph/exams/สถานการณ์สาธารณภัย.json': () => import('../data/paph/exams/สถานการณ์สาธารณภัย.json'),
  '../data/paph/exams/เทคโนโลยีและเครื่องมือวิเคราะห์.json': () => import('../data/paph/exams/เทคโนโลยีและเครื่องมือวิเคราะห์.json'),
  '../data/paph/exams/แผนการป้องกันภัยแห่งชาติ .json': () => import('../data/paph/exams/แผนการป้องกันภัยแห่งชาติ .json'),
  '../data/paph/exams/แผนพัฒนาเศรษฐกิจและสังคม.json': () => import('../data/paph/exams/แผนพัฒนาเศรษฐกิจและสังคม.json'),
};
